assign_02_proj/assign_02_app/urls.py
from django.urls import path
from . import views

app_name = "assign_02_app"
urlpatterns = [
    #  Exercise 1 : use teamplate
    path('ex1/', views.IndexView.as_view(), name='index'),
    path('ex1/<int:person_id>/', views.DetailView.as_view(), name='detail'),


    #  Exercise 2 : use teamplate
    path('ex2/', views.index, name='index'),
    path('ex2/<int:person_id>/', views.detail, name='detail'),

    #  Exercise 3 : form input
    path('', views.formInput, name='formInput'),
]

assign_02_proj/assign_02_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('assign_02_app/', include('assign_02_app.urls'))
]

assign_02_proj/assign_02_app/forms.py
from django import forms
from .models import Person

class PersonForm(forms.ModelForm):
    # specify the name of model to use
    class Meta:
        model = Person
        fields = "__all__"

assign_02_proj/assign_02_app/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Person
from .forms import PersonForm

#  Exercise 1 : use view

class IndexView(generic.ListView):
    template_name = 'assign_02_app/index0.html'
    context_object_name = 'person_list'

    def get_queryset(self):
        return Person.objects.all()

class DetailView(generic.DetailView):
    model = Person
    template_name = 'assign_02_app/detail.html'

#  Exercise 2 : use teamplate
def index(request):
    person_list = Person.objects.order_by('id')[:10]
    context = {'person_list': person_list}
    return render(request, 'assign_02_app/index0.html', context)

def detail(request, person_id):
    try:
        person = Person.objects.get(pk=person_id)
    except Person.DoesNotExist:
        raise Http404("Person does not exist")
    return render(request, 'assign_02_app/detail.html', {'person': person})

# excercise 3 : form
def formInput(request):
    context = {}

    # create object of form
    form = PersonForm(request.POST or None, request.FILES or None)

    # check if form data is valid
    if form.is_valid():
        # save the form data to model
        form.save()

    context['form'] = form
    return render(request, "assign_02_app/form.html", context)

assign_02_proj/assign_02_app/templates/assign_02_app/detail.html
<h2> Person Info Details:</h2>
<h3> ID: {{ object.id }}</h3>
<h3> Name: {{ object.name }}</h3>
<h3> Age: {{ object.age }}</h3>
<h3> Adress: {{ object.address }}</h3>
<h3> Mobile: {{ object.mobile_number }}</h3>

assign_02_proj/assign_02_app/templates/assign_02_app/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form Input</title>
</head>
<body>
<form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
</body>
</html>

assign_02_proj/assign_02_app/templates/assign_02_app/index.html
{% load static %}
<!--<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />-->


{% if person_list %}
    <ul>
    {% for person in person_list %}
        <li><a href="{% url 'assign_02_app:detail' person.id %}">{{ person.name }}</a> - {{ person.age }} - {{ person.address }} - {{ person.mobile_number }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No person are available.</p>
{% endif %}